<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
$routes->get('/', 'PageController::login');
$routes->get('healthz', 'PageController::health');

$routes->post('auth/login', 'AuthController::login');
$routes->post('auth/logout', 'AuthController::logout');
$routes->get('auth/logout', 'AuthController::logout');
$routes->get('auth/me', 'AuthController::me');
$routes->get('auth/select-role', 'AuthController::selectRolePage');
$routes->post('auth/select-role', 'AuthController::selectRole');

$routes->post('pos/transactions', 'PosController::createTransaction', ['filter' => 'access:store.operate']);

$routes->get('login', 'PageController::login');
$routes->get('dashboard', 'PageController::dashboard', ['filter' => 'access:portal.enter']);
$routes->post('profile/image', 'ProfileController::uploadImage', ['filter' => 'access:account.self']);
$routes->get('notifications', 'NotificationController::index', ['filter' => 'access:account.self']);
$routes->post('notifications/(:num)/read', 'NotificationController::markRead/$1', ['filter' => 'access:account.self']);
$routes->post('notifications/read-all', 'NotificationController::markAllRead', ['filter' => 'access:account.self']);

$routes->get('admin/dashboard', 'AdminController::dashboard', ['filter' => 'access:system.manage']);
$routes->get('admin/dashboard/data', 'AdminController::dashboardData', ['filter' => 'access:system.manage']);
$routes->get('admin/store-ops', 'AdminController::storeOps', ['filter' => 'access:system.manage']);
$routes->get('admin/accounting-debts', 'AdminController::accountingDebts', ['filter' => 'access:system.manage']);
$routes->get('admin/accounting-debts/data', 'AdminController::accountingDebtsData', ['filter' => 'access:system.manage']);
$routes->get('admin/accounting-debts/user/(:num)', 'AdminController::accountingDebtUserDetail/$1', ['filter' => 'access:system.manage']);
$routes->get('admin/user-view', 'AdminController::userView', ['filter' => 'access:system.manage']);
$routes->get('admin/user-view/data', 'AdminController::userViewData', ['filter' => 'access:system.manage']);
$routes->get('admin/user-view/(:num)', 'AdminController::userViewDetail/$1', ['filter' => 'access:system.manage']);
$routes->get('admin/salary-schedules', 'AdminController::salarySchedules', ['filter' => 'access:system.manage']);
$routes->post('admin/user-view/create', 'AdminController::createUser', ['filter' => 'access:system.manage']);
$routes->post('admin/user-view/update', 'AdminController::updateUser', ['filter' => 'access:system.manage']);
$routes->post('admin/user-view/import-csv', 'AdminController::importUsersCsv', ['filter' => 'access:system.manage']);
$routes->get('admin/products', 'AdminController::products', ['filter' => 'access:system.manage']);
$routes->get('admin/products/data', 'AdminController::productsData', ['filter' => 'access:system.manage']);
$routes->get('admin/audit', 'AdminController::audit', ['filter' => 'access:system.manage']);
$routes->get('admin/audit/data', 'AdminController::auditData', ['filter' => 'access:system.manage']);
$routes->get('admin/stores', 'AdminController::stores', ['filter' => 'access:system.manage']);
$routes->get('admin/stores/data', 'AdminController::storesData', ['filter' => 'access:system.manage']);
$routes->get('admin/stores/(:num)', 'AdminController::storeDetails/$1', ['filter' => 'access:system.manage']);
$routes->get('admin/stores/(:num)/data', 'AdminController::storeDetailsData/$1', ['filter' => 'access:system.manage']);
$routes->post('admin/store-day-sessions/(:num)/review', 'AdminController::reviewStoreDayVariance/$1', ['filter' => 'access:system.manage']);
$routes->post('admin/store-day-sessions/(:num)/resolve-stale', 'AdminController::resolveStaleStoreDay/$1', ['filter' => 'access:system.manage']);
$routes->post('admin/variance-cases/(:num)/attachments', 'AdminController::uploadVarianceCaseAttachment/$1', ['filter' => 'access:system.manage']);
$routes->get('admin/variance-case-attachments/(:num)', 'AdminController::downloadVarianceCaseAttachment/$1', ['filter' => 'access:system.manage']);
$routes->post('admin/variance-cases/(:num)/handoff', 'AdminController::handoffVarianceCase/$1', ['filter' => 'access:system.manage']);
$routes->post('admin/variance-cases/(:num)/acknowledge', 'AdminController::acknowledgeVarianceCase/$1', ['filter' => 'access:system.manage']);
$routes->get('admin/stores/officers', 'AdminController::officers', ['filter' => 'access:system.manage']);
$routes->post('admin/stores/create', 'AdminController::createStore', ['filter' => 'access:system.manage']);
$routes->post('admin/stores/update', 'AdminController::updateStore', ['filter' => 'access:system.manage']);
$routes->post('admin/stores/toggle-status', 'AdminController::toggleStoreStatus', ['filter' => 'access:system.manage']);

$routes->get('store-admin', 'StoreAdminController::dashboard', ['filter' => 'access:store.review_assigned']);
$routes->get('store-admin/dashboard', 'StoreAdminController::dashboard', ['filter' => 'access:store.review_assigned']);
$routes->get('store-admin/dashboard/data', 'StoreAdminController::dashboardData', ['filter' => 'access:store.review_assigned']);
$routes->get('store-admin/stores', 'StoreAdminController::stores', ['filter' => 'access:store.review_assigned']);
$routes->get('store-admin/stores/data', 'StoreAdminController::storesData', ['filter' => 'access:store.review_assigned']);
$routes->get('store-admin/stores/(:num)', 'StoreAdminController::storeDetails/$1', ['filter' => 'access:store.review_assigned']);
$routes->get('store-admin/stores/(:num)/data', 'StoreAdminController::storeDetailsData/$1', ['filter' => 'access:store.review_assigned']);
$routes->post('store-admin/store-day-sessions/(:num)/review', 'StoreAdminController::reviewStoreDayVariance/$1', ['filter' => 'access:store.review_assigned']);
$routes->post('store-admin/store-day-sessions/(:num)/resolve-stale', 'StoreAdminController::resolveStaleStoreDay/$1', ['filter' => 'access:store.review_assigned']);
$routes->post('store-admin/variance-cases/(:num)/attachments', 'StoreAdminController::uploadVarianceCaseAttachment/$1', ['filter' => 'access:store.review_assigned']);
$routes->get('store-admin/variance-case-attachments/(:num)', 'StoreAdminController::downloadVarianceCaseAttachment/$1', ['filter' => 'access:store.review_assigned']);
$routes->post('store-admin/variance-cases/(:num)/handoff', 'StoreAdminController::handoffVarianceCase/$1', ['filter' => 'access:store.review_assigned']);
$routes->post('store-admin/variance-cases/(:num)/acknowledge', 'StoreAdminController::acknowledgeVarianceCase/$1', ['filter' => 'access:store.review_assigned']);

$routes->get('store/pos', 'StoreController::pos', ['filter' => 'access:store.inspect']);
$routes->get('store/dashboard', 'StoreController::dashboard', ['filter' => 'access:store.inspect']);
$routes->get('store/history', 'StoreController::history', ['filter' => 'access:store.inspect']);
$routes->get('store/inventory', 'StoreController::inventory', ['filter' => 'access:store.inspect']);
$routes->get('store/reports', 'StoreController::reports', ['filter' => 'access:store.inspect']);
$routes->get('store/staff-records', 'StoreController::staffRecords', ['filter' => 'access:store.inspect']);
$routes->get('store/settings', 'StoreController::settings', ['filter' => 'access:store.inspect']);
$routes->get('store/my-stores', 'StoreController::myStores', ['filter' => 'access:store.inspect']);
$routes->get('store/products', 'StoreController::products', ['filter' => 'access:store.inspect']);
$routes->get('store/categories', 'StoreController::categories', ['filter' => 'access:store.inspect']);
$routes->post('store/categories/create', 'StoreController::createCategory', ['filter' => 'access:store.operate']);
$routes->post('store/categories/update', 'StoreController::updateCategory', ['filter' => 'access:store.operate']);
$routes->post('store/categories/delete', 'StoreController::deleteCategory', ['filter' => 'access:store.operate']);
$routes->get('store/payment-methods', 'StoreController::paymentMethods', ['filter' => 'access:store.inspect']);
$routes->post('store/payment-methods/create', 'StoreController::createPaymentMethod', ['filter' => 'access:store.operate']);
$routes->post('store/payment-methods/update', 'StoreController::updatePaymentMethod', ['filter' => 'access:store.operate']);
$routes->post('store/payment-methods/delete', 'StoreController::deletePaymentMethod', ['filter' => 'access:store.operate']);
$routes->get('store/payment-accounts', 'StoreController::paymentAccounts', ['filter' => 'access:store.inspect']);
$routes->post('store/payment-accounts/save', 'StoreController::savePaymentAccount', ['filter' => 'access:store.operate']);
$routes->post('store/payment-accounts/upload-qr', 'StoreController::uploadPaymentAccountQr', ['filter' => 'access:store.operate']);
$routes->post('store/payment-methods/upload-image', 'StoreController::uploadPaymentMethodImage', ['filter' => 'access:store.operate']);
$routes->post('store/payment-accounts/deactivate', 'StoreController::deactivatePaymentAccount', ['filter' => 'access:store.operate']);
$routes->get('store/day-session/status', 'StoreController::daySessionStatus', ['filter' => 'access:store.inspect']);
$routes->post('store/day-session/open', 'StoreController::openDaySession', ['filter' => 'access:store.operate']);
$routes->post('store/day-session/close', 'StoreController::closeDaySession', ['filter' => 'access:store.operate']);
$routes->get('store/opening-balance/status', 'StoreController::openingBalanceStatus', ['filter' => 'access:store.inspect']);
$routes->post('store/opening-balance/set', 'StoreController::setOpeningBalance', ['filter' => 'access:store.operate']);
$routes->post('store/opening-balance/reset', 'StoreController::resetOpeningBalance', ['filter' => 'access:system.manage']);
$routes->get('store/cash-movements', 'StoreController::cashMovements', ['filter' => 'access:store.inspect']);
$routes->post('store/cash-movements/create', 'StoreController::createCashMovement', ['filter' => 'access:store.operate']);
$routes->post('store/debt-repayments/create', 'StoreController::createDebtRepayment', ['filter' => 'access:store.operate']);
$routes->get('store/reports/summary', 'StoreController::reportSummary', ['filter' => 'access:store.inspect']);
$routes->get('store/debt-customers', 'StoreController::debtCustomers', ['filter' => 'access:store.inspect']);
$routes->get('store/transactions', 'StoreController::transactions', ['filter' => 'access:store.inspect']);
$routes->get('store/staff-transactions', 'StoreController::staffTransactions', ['filter' => 'access:store.inspect']);
$routes->get('store/transactions/(:num)', 'StoreController::transactionDetails/$1', ['filter' => 'access:store.inspect']);
$routes->get('store/receipt/(:num)', 'StoreController::receiptPage/$1', ['filter' => 'access:store.inspect']);
$routes->get('store/inventory/movements', 'StoreController::inventoryMovements', ['filter' => 'access:store.inspect']);
$routes->post('store/inventory/restock', 'StoreController::restock', ['filter' => 'access:store.operate']);
$routes->post('store/inventory/adjust-stock', 'StoreController::adjustStock', ['filter' => 'access:store.operate']);
$routes->post('store/inventory/add-product', 'StoreController::addProduct', ['filter' => 'access:store.operate']);
$routes->post('store/inventory/add-product-family', 'StoreController::addProductFamily', ['filter' => 'access:store.operate']);
$routes->post('store/inventory/update-product', 'StoreController::updateProduct', ['filter' => 'access:store.operate']);

$routes->get('user/dashboard', 'UserController::dashboard', ['filter' => 'access:user.self']);
$routes->get('user/dashboard/data', 'UserController::dashboardData', ['filter' => 'access:user.self']);
$routes->get('user/debt-pin/status', 'UserController::debtPinStatus', ['filter' => 'access:user.self']);
$routes->post('user/debt-pin/set', 'UserController::setDebtPin', ['filter' => 'access:user.self']);
$routes->get('user/history', 'UserController::history', ['filter' => 'access:user.self']);
$routes->get('user/stores', 'UserController::stores', ['filter' => 'access:user.self']);
$routes->get('user/stores/data', 'UserController::storesData', ['filter' => 'access:user.self']);
$routes->get('user/deductions', 'UserController::deductions', ['filter' => 'access:user.self']);
$routes->get('user/deductions/data', 'UserController::deductionsData', ['filter' => 'access:user.self']);
$routes->get('user/summary', 'UserController::summary', ['filter' => 'access:user.self']);
$routes->get('user/transactions', 'UserController::transactions', ['filter' => 'access:user.self']);
$routes->get('user/transactions/(:num)', 'UserController::transactionDetails/$1', ['filter' => 'access:user.self']);
$routes->get('user/receipt/(:num)', 'UserController::receiptPage/$1', ['filter' => 'access:user.self']);
$routes->get('user/cashbook', 'UserController::cashbook', ['filter' => 'access:user.self']);

$routes->get('accounting/dashboard', 'AccountingController::dashboard', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/dashboard/data', 'AccountingController::dashboardData', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/debts', 'AccountingController::debts', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/deductions', 'AccountingController::deductions', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/debts/data', 'AccountingController::debtsData', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/debts/profile', 'AccountingController::debtProfile', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/salary-schedules', 'AccountingController::salarySchedules', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/debts/history', 'AccountingController::debtHistory', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/debts/daily-summary', 'AccountingController::dailySummary', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/deduction-workflow', 'AccountingController::deductionWorkflowData', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/debt-investigations', 'AccountingController::debtInvestigationsData', ['filter' => 'access:accounting.inspect']);
$routes->post('accounting/debt-investigations', 'AccountingController::openDebtInvestigation', ['filter' => 'access:accounting.operate']);
$routes->post('accounting/debt-investigations/(:num)/recommend', 'AccountingController::recommendDebtInvestigation/$1', ['filter' => 'access:accounting.operate']);
$routes->post('accounting/debt-investigations/(:num)/approve', 'AccountingController::approveDebtInvestigation/$1', ['filter' => 'access:accounting.operate']);
$routes->post('accounting/deduction-periods', 'AccountingController::createDeductionPeriod', ['filter' => 'access:accounting.operate']);
$routes->post('accounting/deduction-batches', 'AccountingController::prepareDeductionBatch', ['filter' => 'access:accounting.operate']);
$routes->post('accounting/deduction-batches/(:num)/apply', 'AccountingController::applyDeductionBatch/$1', ['filter' => 'access:accounting.operate']);
$routes->post('accounting/deduction-batches/(:num)/reconcile', 'AccountingController::reconcileDeductionBatch/$1', ['filter' => 'access:accounting.operate']);
$routes->post('accounting/deduction-batches/(:num)/finalize', 'AccountingController::finalizeDeductionBatch/$1', ['filter' => 'access:accounting.operate']);
$routes->get('accounting/settlement/preview', 'AccountingController::settlementPreview', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/settlement/runs', 'AccountingController::settlementRuns', ['filter' => 'access:accounting.inspect']);
$routes->get('accounting/settlement/runs/(:num)', 'AccountingController::settlementRunDetails/$1', ['filter' => 'access:accounting.inspect']);
$routes->post('accounting/debts/preview-csv', 'AccountingController::previewImportCsv', ['filter' => 'access:accounting.inspect']);
$routes->post('accounting/debts/import-csv', 'AccountingController::importCsv', ['filter' => 'access:accounting.operate']);
$routes->post('accounting/debts/financial-profile', 'AccountingController::updateFinancialProfile', ['filter' => 'access:accounting.operate']);
