<?php

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Config\Database;

class IbemsRepairProductFamilies extends BaseCommand
{
    protected $group = 'IBEMS';
    protected $name = 'ibems:repair-product-families';
    protected $description = 'Idempotently repair the PostgreSQL product-family schema without replaying baseline migrations.';

    public function run(array $params)
    {
        $db = Database::connect();
        if (strtolower((string) $db->DBDriver) !== 'postgre') {
            CLI::error('This repair command is restricted to PostgreSQL.');
            return EXIT_ERROR;
        }

        $db->transException(true)->transStart();
        try {
            $db->query(<<<'SQL'
CREATE TABLE IF NOT EXISTS public.product_families (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    name varchar(150) NOT NULL,
    category varchar(100) NOT NULL DEFAULT 'General',
    supplier varchar(120),
    image_url varchar(255),
    option_name varchar(80) NOT NULL DEFAULT 'Size',
    created_at timestamp without time zone,
    updated_at timestamp without time zone
)
SQL);
            $db->query('ALTER TABLE public.products ADD COLUMN IF NOT EXISTS family_id bigint');
            $db->query(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'products_family_id_fkey') THEN
        ALTER TABLE public.products
            ADD CONSTRAINT products_family_id_fkey
            FOREIGN KEY (family_id) REFERENCES public.product_families(id) ON DELETE SET NULL;
    END IF;
END $$
SQL);
            $db->query('CREATE INDEX IF NOT EXISTS idx_products_family ON public.products (family_id)');
            $db->transComplete();
        } catch (\Throwable $exception) {
            $db->transRollback();
            CLI::error('Product-family schema repair failed: ' . $exception->getMessage());
            return EXIT_ERROR;
        }

        CLI::write('Product-family schema is ready.', 'green');
        return EXIT_SUCCESS;
    }
}
