<?php

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Config\Database;

class IbemsRepairVarianceCases extends BaseCommand
{
    protected $group = 'IBEMS';
    protected $name = 'ibems:repair-variance-cases';
    protected $description = 'Idempotently repair PostgreSQL store-day variance case tables without replaying baseline migrations.';

    public function run(array $params)
    {
        $db = Database::connect();
        if (strtolower((string) $db->DBDriver) !== 'postgre') {
            CLI::error('This repair command is restricted to PostgreSQL.');
            return EXIT_ERROR;
        }

        $db->transException(true)->transStart();
        try {
            $db->query(<<<'SQL'
CREATE TABLE IF NOT EXISTS public.store_day_variance_cases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_ref varchar(40) NOT NULL UNIQUE,
    store_day_session_id bigint NOT NULL UNIQUE,
    store_id bigint NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'open',
    owner_user_id bigint,
    opened_by bigint,
    opened_at timestamp without time zone,
    resolved_by bigint,
    resolved_at timestamp without time zone,
    disposition varchar(40),
    created_at timestamp without time zone,
    updated_at timestamp without time zone
)
SQL);
            $db->query('CREATE INDEX IF NOT EXISTS idx_variance_cases_store_status ON public.store_day_variance_cases (store_id, status)');
            $db->query(<<<'SQL'
CREATE TABLE IF NOT EXISTS public.store_day_variance_case_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    actor_id bigint,
    event_type varchar(40) NOT NULL,
    from_status varchar(30),
    to_status varchar(30),
    note text,
    evidence_json text,
    created_at timestamp without time zone
)
SQL);
            $db->query('CREATE INDEX IF NOT EXISTS idx_variance_events_case_created ON public.store_day_variance_case_events (case_id, created_at)');
            $db->query(<<<'SQL'
CREATE TABLE IF NOT EXISTS public.store_day_variance_case_attachments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    uploaded_by bigint NOT NULL,
    original_name varchar(255) NOT NULL,
    stored_name varchar(80) NOT NULL,
    mime_type varchar(100) NOT NULL,
    file_size bigint NOT NULL,
    sha256 char(64) NOT NULL,
    description varchar(255),
    retention_until date,
    created_at timestamp without time zone
)
SQL);
            $db->query('CREATE INDEX IF NOT EXISTS idx_variance_attachments_case_created ON public.store_day_variance_case_attachments (case_id, created_at)');
            $db->query(<<<'SQL'
CREATE TABLE IF NOT EXISTS public.store_day_variance_case_handoffs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL,
    from_user_id bigint NOT NULL,
    to_user_id bigint NOT NULL,
    note varchar(255) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'pending',
    created_at timestamp without time zone,
    due_at timestamp without time zone,
    acknowledged_by bigint,
    acknowledged_at timestamp without time zone
)
SQL);
            $db->query('CREATE INDEX IF NOT EXISTS idx_variance_handoffs_recipient_status ON public.store_day_variance_case_handoffs (to_user_id, status)');
            $db->query('CREATE INDEX IF NOT EXISTS idx_variance_handoffs_case_created ON public.store_day_variance_case_handoffs (case_id, created_at)');
            $db->query(<<<'SQL'
INSERT INTO public.store_day_variance_cases
    (case_ref, store_day_session_id, store_id, status, owner_user_id, opened_by, opened_at, resolved_by, resolved_at, disposition, created_at, updated_at)
SELECT
    'SDV-' || REPLACE(CAST(s.business_date AS varchar), '-', '') || '-' || LPAD(CAST(s.id AS varchar), 6, '0'),
    s.id,
    s.store_id,
    CASE WHEN s.review_status IN ('approved', 'waived', 'corrected') THEN 'resolved'
         WHEN s.review_status = 'needs_investigation' THEN 'investigating' ELSE 'open' END,
    CASE WHEN s.review_status IN ('approved', 'waived', 'corrected') THEN NULL ELSE s.reviewed_by END,
    s.closed_by,
    COALESCE(s.closed_at, s.updated_at, CURRENT_TIMESTAMP),
    CASE WHEN s.review_status IN ('approved', 'waived', 'corrected') THEN s.reviewed_by ELSE NULL END,
    CASE WHEN s.review_status IN ('approved', 'waived', 'corrected') THEN s.reviewed_at ELSE NULL END,
    CASE WHEN s.review_status IN ('approved', 'waived', 'corrected') THEN s.review_status ELSE NULL END,
    COALESCE(s.closed_at, s.updated_at, CURRENT_TIMESTAMP),
    COALESCE(s.reviewed_at, s.updated_at, CURRENT_TIMESTAMP)
FROM public.store_day_sessions s
WHERE s.review_status <> 'not_required'
ON CONFLICT (store_day_session_id) DO NOTHING
SQL);
            $db->transComplete();
        } catch (\Throwable $exception) {
            $db->transRollback();
            CLI::error('Variance-case schema repair failed: ' . $exception->getMessage());
            return EXIT_ERROR;
        }

        foreach (['store_day_variance_cases', 'store_day_variance_case_events', 'store_day_variance_case_attachments', 'store_day_variance_case_handoffs'] as $table) {
            if (!$db->tableExists($table)) {
                CLI::error('Variance-case schema verification failed: missing ' . $table);
                return EXIT_ERROR;
            }
        }
        CLI::write('Store-day variance case schema is ready.', 'green');
        return EXIT_SUCCESS;
    }
}
