-- IBEMS PostgreSQL baseline for an empty Supabase staging project.
-- Generated from the validated MariaDB schema on 2026-08-11.
-- This script is intentionally idempotent only at the schema level: run it once
-- on an empty database, then manage later changes with versioned migrations.

begin;

create table if not exists public.ibems_schema_meta (
    version varchar(40) primary key,
    applied_at timestamp without time zone not null default current_timestamp,
    description text not null
);

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    employee_id varchar(50) unique,
    name varchar(150) not null,
    email varchar(150) not null unique,
    password_hash varchar(255) not null,
    debt_pin_hash varchar(255),
    profile_image_url varchar(255),
    role varchar(40) not null check (role in ('USER','STORE_SYSTEM','STORE_SUPERVISOR','ACCOUNTING_OFFICE','ADMIN')),
    user_type varchar(20) not null check (user_type in ('faculty','staff','student')),
    qr_token varchar(255) not null unique,
    base_salary numeric(12,2) not null default 0 check (base_salary >= 0),
    employment_type varchar(20) check (employment_type is null or employment_type in ('plantilla','cos','part_time')),
    salary_grade varchar(30),
    salary_step smallint check (salary_step is null or salary_step between 1 and 8),
    salary_effective_date date,
    is_active boolean not null default true,
    created_at timestamp without time zone
);

create table if not exists public.user_roles (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    role varchar(40) not null check (role in ('USER','STORE_SYSTEM','STORE_SUPERVISOR','ACCOUNTING_OFFICE','ADMIN')),
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    unique (user_id, role)
);

create table if not exists public.balances (
    user_id bigint primary key references public.users(id) on delete cascade,
    credit_limit numeric(12,2) not null default 0 check (credit_limit >= 0),
    current_debt numeric(12,2) not null default 0 check (current_debt >= 0),
    updated_at timestamp without time zone
);

create table if not exists public.stores (
    id bigint generated by default as identity primary key,
    store_name varchar(150) not null unique,
    officer_id bigint references public.users(id) on delete set null,
    logo_url varchar(255),
    is_active boolean not null default true,
    created_at timestamp without time zone
);

create table if not exists public.store_supervisors (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on delete cascade,
    user_id bigint not null references public.users(id) on delete cascade,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    unique (store_id, user_id)
);

create table if not exists public.store_categories (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on delete cascade,
    name varchar(100) not null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    unique (store_id, name)
);
create index if not exists store_categories_active_idx on public.store_categories(store_id, is_active);

create table if not exists public.store_payment_methods (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on delete cascade,
    code varchar(50) not null,
    label varchar(100) not null,
    icon_class varchar(80),
    image_url varchar(500),
    sort_order integer not null default 0,
    is_active boolean not null default true,
    is_system_reserved boolean not null default false,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    unique (store_id, code)
);
create index if not exists store_payment_methods_active_idx on public.store_payment_methods(store_id, is_active);

create table if not exists public.product_families (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on delete cascade,
    name varchar(150) not null,
    category varchar(100) not null default 'General', supplier varchar(120), image_url varchar(255),
    option_name varchar(80) not null default 'Size', created_at timestamp without time zone, updated_at timestamp without time zone
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on delete restrict,
    family_id bigint references public.product_families(id) on delete set null,
    sku varchar(50) not null,
    name varchar(150) not null,
    variant_label varchar(80),
    category varchar(100) not null default 'General',
    supplier varchar(120),
    image_url varchar(255),
    barcode varchar(100),
    price numeric(12,2) not null check (price >= 0),
    stock_qty integer not null default 0 check (stock_qty >= 0),
    low_stock_threshold integer not null default 10 check (low_stock_threshold >= 0),
    location_bin varchar(120),
    is_active boolean not null default true,
    updated_at timestamp without time zone,
    unique (store_id, sku)
);
create index if not exists products_store_barcode_idx on public.products(store_id, barcode);

create table if not exists public.store_day_sessions (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on delete restrict,
    business_date date not null,
    status varchar(20) not null default 'open' check (status in ('open','closed')),
    opening_cash numeric(12,2) not null default 0 check (opening_cash >= 0),
    opening_ecash numeric(12,2) not null default 0 check (opening_ecash >= 0),
    opening_note varchar(255),
    opened_by bigint references public.users(id) on delete set null,
    opened_at timestamp without time zone,
    expected_cash numeric(12,2),
    expected_ecash numeric(12,2),
    counted_cash numeric(12,2),
    counted_ecash numeric(12,2),
    variance_cash numeric(12,2),
    variance_ecash numeric(12,2),
    variance_status varchar(20) default 'balanced',
    review_status varchar(20) default 'not_required',
    reviewed_by bigint references public.users(id) on delete set null,
    reviewed_at timestamp without time zone,
    review_note varchar(255),
    accountability_user_id bigint references public.users(id) on delete set null,
    accountability_amount numeric(12,2) default 0 check (accountability_amount >= 0),
    closing_note varchar(255),
    closed_by bigint references public.users(id) on delete set null,
    closed_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    unique (store_id, business_date)
);

create table if not exists public.store_opening_balances (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on delete restrict,
    business_date date not null,
    opening_balance numeric(12,2) not null default 0 check (opening_balance >= 0),
    note varchar(255),
    opened_by bigint references public.users(id) on delete set null,
    opened_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    unique (store_id, business_date)
);

create table if not exists public.store_cash_movements (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on delete restrict,
    business_date date not null,
    channel varchar(16) not null default 'cash' check (channel in ('cash','ecash')),
    movement_type varchar(16) not null check (movement_type in ('cash_in','cash_out')),
    amount numeric(12,2) not null default 0 check (amount >= 0),
    reason varchar(255) not null,
    created_by bigint references public.users(id) on delete set null,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);
create index if not exists store_cash_movements_date_idx on public.store_cash_movements(store_id, business_date);

create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    client_txn_id varchar(100) not null unique,
    user_id bigint references public.users(id) on delete set null,
    customer_type varchar(20) not null check (customer_type in ('faculty','staff','student','walk_in')),
    store_id bigint not null references public.stores(id) on delete restrict,
    amount numeric(12,2) not null check (amount >= 0),
    payment_method varchar(50) not null,
    other_payment_label varchar(100),
    status varchar(50) not null default 'completed',
    reference_no varchar(100),
    created_at timestamp without time zone,
    synced_at timestamp without time zone
);
create index if not exists transactions_user_idx on public.transactions(user_id);
create index if not exists transactions_store_created_idx on public.transactions(store_id, created_at);

create table if not exists public.transaction_payments (
    id bigint generated by default as identity primary key,
    transaction_id bigint not null references public.transactions(id) on delete cascade,
    payment_method varchar(50) not null,
    amount numeric(12,2) not null check (amount > 0),
    cash_received numeric(12,2),
    change_due numeric(12,2),
    created_at timestamp without time zone
);
create index if not exists transaction_payments_transaction_method_idx on public.transaction_payments(transaction_id, payment_method);

create table if not exists public.transaction_items (
    id bigint generated by default as identity primary key,
    transaction_id bigint not null references public.transactions(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete restrict,
    qty integer not null check (qty > 0),
    unit_price numeric(12,2) not null check (unit_price >= 0),
    line_total numeric(12,2) not null check (line_total >= 0),
    created_at timestamp without time zone
);
create index if not exists transaction_items_product_idx on public.transaction_items(product_id);

create table if not exists public.inventory_movements (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete restrict,
    store_id bigint not null references public.stores(id) on delete restrict,
    type varchar(20) not null check (type in ('sale','restock','adjustment')),
    qty integer not null,
    unit_cost numeric(12,2) check (unit_cost >= 0),
    total_cost numeric(12,2) check (total_cost >= 0),
    expected_profit numeric(12,2),
    reason varchar(255),
    txn_id bigint references public.transactions(id) on delete set null,
    created_at timestamp without time zone
);
create index if not exists inventory_movements_product_idx on public.inventory_movements(product_id);
create index if not exists inventory_movements_store_idx on public.inventory_movements(store_id);
create index if not exists inventory_movements_txn_idx on public.inventory_movements(txn_id);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id) on delete set null,
    txn_id bigint not null references public.transactions(id) on delete cascade,
    channel varchar(50) not null,
    status varchar(50) not null,
    sent_at timestamp without time zone,
    error_msg text
);

create table if not exists public.salary_import_batches (
    id bigint generated by default as identity primary key,
    filename varchar(255) not null,
    imported_by bigint not null references public.users(id) on delete restrict,
    imported_at timestamp without time zone,
    total_rows integer not null default 0 check (total_rows >= 0),
    valid_rows integer not null default 0 check (valid_rows >= 0),
    invalid_rows integer not null default 0 check (invalid_rows >= 0)
);

create table if not exists public.salary_import_rows (
    id bigint generated by default as identity primary key,
    batch_id bigint not null references public.salary_import_batches(id) on delete cascade,
    employee_id varchar(50),
    name varchar(150),
    email varchar(150),
    monthly_salary numeric(12,2) not null default 0 check (monthly_salary >= 0),
    status varchar(20) not null default 'valid' check (status in ('valid','invalid')),
    error_msg text
);

create table if not exists public.settlement_runs (
    id bigint generated by default as identity primary key,
    run_month varchar(7) not null unique,
    run_by bigint not null references public.users(id) on delete restrict,
    run_at timestamp without time zone,
    total_accounts integer not null default 0 check (total_accounts >= 0),
    total_debt_before numeric(12,2) not null default 0 check (total_debt_before >= 0),
    notes text
);

create table if not exists public.deduction_periods (
    id bigint generated by default as identity primary key,
    period_code varchar(40) not null unique,
    label varchar(120) not null,
    frequency varchar(20) not null check (frequency in ('semi_monthly','monthly','custom')),
    date_start date not null,
    date_end date not null,
    expected_processing_date date,
    preparation_deadline date,
    status varchar(30) not null default 'draft',
    notes text,
    created_by bigint references public.users(id) on delete set null,
    reviewed_by bigint references public.users(id) on delete set null,
    submitted_by bigint references public.users(id) on delete set null,
    confirmed_by bigint references public.users(id) on delete set null,
    finalized_by bigint references public.users(id) on delete set null,
    reviewed_at timestamp without time zone,
    submitted_at timestamp without time zone,
    confirmed_at timestamp without time zone,
    finalized_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    check (date_end >= date_start)
);
create index if not exists deduction_periods_dates_idx on public.deduction_periods(date_start, date_end);
create index if not exists deduction_periods_status_idx on public.deduction_periods(status);

create table if not exists public.deduction_batches (
    id bigint generated by default as identity primary key,
    period_id bigint not null unique references public.deduction_periods(id) on delete restrict,
    status varchar(30) not null default 'draft',
    total_accounts integer not null default 0 check (total_accounts >= 0),
    total_requested numeric(12,2) not null default 0 check (total_requested >= 0),
    total_confirmed numeric(12,2) not null default 0 check (total_confirmed >= 0),
    total_carryover numeric(12,2) not null default 0 check (total_carryover >= 0),
    legacy_settlement_run_id bigint unique references public.settlement_runs(id) on delete set null,
    notes text,
    created_by bigint references public.users(id) on delete set null,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);
create index if not exists deduction_batches_status_idx on public.deduction_batches(status);

create table if not exists public.deduction_batch_items (
    id bigint generated by default as identity primary key,
    batch_id bigint not null references public.deduction_batches(id) on delete cascade,
    user_id bigint not null references public.users(id) on delete restrict,
    debt_snapshot numeric(12,2) not null default 0 check (debt_snapshot >= 0),
    requested_amount numeric(12,2) not null default 0 check (requested_amount >= 0),
    confirmed_amount numeric(12,2) not null default 0 check (confirmed_amount >= 0),
    carryover_amount numeric(12,2) not null default 0 check (carryover_amount >= 0),
    result_status varchar(40) not null default 'pending',
    reason_code varchar(50),
    result_reference varchar(120),
    result_notes text,
    confirmed_by bigint references public.users(id) on delete set null,
    confirmed_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    unique (batch_id, user_id),
    check (confirmed_amount <= requested_amount)
);
create index if not exists deduction_batch_items_result_idx on public.deduction_batch_items(user_id, result_status);

create table if not exists public.debt_pin_security (
    user_id bigint primary key references public.users(id) on delete cascade,
    failed_attempts integer not null default 0 check (failed_attempts between 0 and 5),
    window_started_at timestamp without time zone,
    locked_until timestamp without time zone,
    last_failed_at timestamp without time zone,
    last_success_at timestamp without time zone,
    updated_at timestamp without time zone
);
create index if not exists debt_pin_security_locked_idx on public.debt_pin_security(locked_until);

create table if not exists public.debt_cashbook_entries (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete restrict,
    entry_type varchar(40) not null,
    direction varchar(10) not null check (direction in ('debit','credit')),
    amount numeric(12,2) not null default 0 check (amount >= 0),
    debt_before numeric(12,2) not null default 0 check (debt_before >= 0),
    debt_after numeric(12,2) not null default 0 check (debt_after >= 0),
    credit_limit_snapshot numeric(12,2) not null default 0 check (credit_limit_snapshot >= 0),
    available_credit_snapshot numeric(12,2) not null default 0 check (available_credit_snapshot >= 0),
    reference_type varchar(30),
    reference_id bigint,
    actor_id bigint references public.users(id) on delete set null,
    remarks varchar(255),
    meta_json text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);
create index if not exists debt_cashbook_user_created_idx on public.debt_cashbook_entries(user_id, created_at);
create index if not exists debt_cashbook_reference_idx on public.debt_cashbook_entries(reference_type, reference_id);

create table if not exists public.debt_investigations (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete restrict,
    transaction_id bigint references public.transactions(id) on delete set null,
    status varchar(30) not null default 'open',
    issue_type varchar(50) not null,
    summary text not null,
    evidence_summary text,
    findings text,
    recommended_action varchar(40),
    recommended_amount numeric(12,2) not null default 0 check (recommended_amount >= 0),
    rejection_reason text,
    reversal_cashbook_entry_id bigint references public.debt_cashbook_entries(id) on delete set null,
    opened_by bigint references public.users(id) on delete set null,
    investigator_id bigint references public.users(id) on delete set null,
    recommended_by bigint references public.users(id) on delete set null,
    approved_by bigint references public.users(id) on delete set null,
    posted_by bigint references public.users(id) on delete set null,
    recommended_at timestamp without time zone,
    approved_at timestamp without time zone,
    posted_at timestamp without time zone,
    closed_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);
create index if not exists debt_investigations_user_status_idx on public.debt_investigations(user_id, status);
create index if not exists debt_investigations_transaction_idx on public.debt_investigations(transaction_id);

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    actor_id bigint references public.users(id) on delete set null,
    action varchar(100) not null,
    entity varchar(100) not null,
    entity_id bigint,
    payload_json text,
    created_at timestamp without time zone
);
create index if not exists audit_logs_actor_idx on public.audit_logs(actor_id);
create index if not exists audit_logs_created_idx on public.audit_logs(created_at);

insert into public.ibems_schema_meta(version, description)
values ('2026-08-11-baseline', 'Initial IBEMS PostgreSQL staging baseline')
on conflict (version) do nothing;

commit;
