begin;

create table if not exists public.transaction_payments (
    id bigint generated by default as identity primary key,
    transaction_id bigint not null references public.transactions(id) on delete cascade,
    payment_method varchar(50) not null,
    amount numeric(12,2) not null check (amount > 0),
    cash_received numeric(12,2),
    change_due numeric(12,2),
    created_at timestamp without time zone
);

create index if not exists transaction_payments_transaction_method_idx
    on public.transaction_payments(transaction_id, payment_method);

commit;
