begin;

alter table public.stores add column if not exists deactivated_at timestamp without time zone;
alter table public.stores add column if not exists deactivated_by bigint references public.users(id) on delete set null;
alter table public.stores add column if not exists deactivation_reason text;
alter table public.stores add column if not exists reactivated_at timestamp without time zone;
alter table public.stores add column if not exists reactivated_by bigint references public.users(id) on delete set null;

create table if not exists public.store_supervisor_assignment_history (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on delete restrict,
    user_id bigint not null references public.users(id) on delete restrict,
    assigned_at timestamp without time zone not null,
    assigned_by bigint references public.users(id) on delete set null,
    ended_at timestamp without time zone,
    ended_by bigint references public.users(id) on delete set null,
    check (ended_at is null or ended_at >= assigned_at)
);

create index if not exists store_supervisor_history_store_active_idx
    on public.store_supervisor_assignment_history(store_id, ended_at);
create index if not exists store_supervisor_history_user_active_idx
    on public.store_supervisor_assignment_history(user_id, ended_at);

insert into public.store_supervisor_assignment_history (
    store_id, user_id, assigned_at, assigned_by
)
select
    ss.store_id,
    ss.user_id,
    coalesce(ss.created_at, current_timestamp),
    null
from public.store_supervisors ss
where not exists (
    select 1
    from public.store_supervisor_assignment_history history
    where history.store_id = ss.store_id
      and history.user_id = ss.user_id
      and history.ended_at is null
);

insert into public.ibems_schema_meta (version, description)
values ('2026-08-13-store-lifecycle', 'Add guarded store lifecycle metadata and effective-dated supervisor assignment history')
on conflict (version) do nothing;

commit;
