begin;

create table if not exists public.store_day_variance_cases (
    id bigint generated by default as identity primary key,
    case_ref varchar(40) not null unique,
    store_day_session_id bigint not null unique references public.store_day_sessions(id) on delete restrict,
    store_id bigint not null references public.stores(id) on delete restrict,
    status varchar(30) not null default 'open' check (status in ('open', 'investigating', 'resolved')),
    owner_user_id bigint references public.users(id) on delete set null,
    opened_by bigint references public.users(id) on delete set null,
    opened_at timestamp without time zone,
    resolved_by bigint references public.users(id) on delete set null,
    resolved_at timestamp without time zone,
    disposition varchar(40),
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    check ((status = 'resolved' and resolved_at is not null and disposition is not null) or status <> 'resolved')
);
create index if not exists variance_cases_store_status_idx
    on public.store_day_variance_cases(store_id, status);

create table if not exists public.store_day_variance_case_events (
    id bigint generated by default as identity primary key,
    case_id bigint not null references public.store_day_variance_cases(id) on delete cascade,
    actor_id bigint references public.users(id) on delete set null,
    event_type varchar(40) not null,
    from_status varchar(30),
    to_status varchar(30),
    note text,
    evidence_json text,
    created_at timestamp without time zone
);
create index if not exists variance_case_events_case_created_idx
    on public.store_day_variance_case_events(case_id, created_at);

create table if not exists public.store_day_variance_case_attachments (
    id bigint generated by default as identity primary key,
    case_id bigint not null references public.store_day_variance_cases(id) on delete cascade,
    uploaded_by bigint not null references public.users(id) on delete restrict,
    original_name varchar(255) not null,
    stored_name varchar(80) not null,
    mime_type varchar(100) not null,
    file_size bigint not null check (file_size >= 0),
    sha256 char(64) not null,
    description varchar(255),
    retention_until date not null default ((current_date + interval '7 years')::date),
    created_at timestamp without time zone
);
create index if not exists variance_case_attachments_case_created_idx
    on public.store_day_variance_case_attachments(case_id, created_at);

create table if not exists public.store_day_variance_case_handoffs (
    id bigint generated by default as identity primary key,
    case_id bigint not null references public.store_day_variance_cases(id) on delete cascade,
    from_user_id bigint not null references public.users(id) on delete restrict,
    to_user_id bigint not null references public.users(id) on delete restrict,
    note varchar(255) not null,
    status varchar(30) not null default 'pending' check (status in ('pending', 'acknowledged')),
    created_at timestamp without time zone,
    due_at timestamp without time zone not null default (current_timestamp + interval '48 hours'),
    acknowledged_by bigint references public.users(id) on delete restrict,
    acknowledged_at timestamp without time zone,
    check (from_user_id <> to_user_id),
    check ((status = 'acknowledged' and acknowledged_by is not null and acknowledged_at is not null) or status = 'pending')
);
create index if not exists variance_case_handoffs_recipient_status_idx
    on public.store_day_variance_case_handoffs(to_user_id, status);
create index if not exists variance_case_handoffs_case_created_idx
    on public.store_day_variance_case_handoffs(case_id, created_at);

insert into public.store_day_variance_cases (
    case_ref, store_day_session_id, store_id, status, owner_user_id,
    opened_by, opened_at, resolved_by, resolved_at, disposition, created_at, updated_at
)
select
    'SDV-' || to_char(sds.business_date, 'YYYYMMDD') || '-' || lpad(sds.id::text, 6, '0'),
    sds.id,
    sds.store_id,
    case
        when sds.review_status in ('approved', 'waived', 'corrected') then 'resolved'
        when sds.review_status = 'needs_investigation' then 'investigating'
        else 'open'
    end,
    case when sds.review_status in ('approved', 'waived', 'corrected') then null else sds.reviewed_by end,
    sds.closed_by,
    coalesce(sds.closed_at, sds.updated_at, current_timestamp),
    case when sds.review_status in ('approved', 'waived', 'corrected') then sds.reviewed_by end,
    case when sds.review_status in ('approved', 'waived', 'corrected') then sds.reviewed_at end,
    case when sds.review_status in ('approved', 'waived', 'corrected') then sds.review_status end,
    coalesce(sds.closed_at, sds.updated_at, current_timestamp),
    coalesce(sds.reviewed_at, sds.updated_at, sds.closed_at, current_timestamp)
from public.store_day_sessions sds
where coalesce(sds.review_status, 'not_required') <> 'not_required'
  and not exists (
      select 1 from public.store_day_variance_cases existing
      where existing.store_day_session_id = sds.id
  );

insert into public.store_day_variance_case_events (
    case_id, actor_id, event_type, to_status, note, evidence_json, created_at
)
select
    variance_case.id,
    coalesce(sds.reviewed_by, sds.closed_by),
    'legacy_snapshot',
    sds.review_status,
    coalesce(sds.review_note, sds.closing_note, 'Variance imported from the store-day record.'),
    json_build_object(
        'business_date', sds.business_date,
        'expected_cash', sds.expected_cash,
        'expected_ecash', sds.expected_ecash,
        'counted_cash', sds.counted_cash,
        'counted_ecash', sds.counted_ecash,
        'variance_cash', sds.variance_cash,
        'variance_ecash', sds.variance_ecash,
        'variance_status', sds.variance_status,
        'review_status', sds.review_status,
        'closing_note', sds.closing_note
    )::text,
    coalesce(sds.reviewed_at, sds.updated_at, sds.closed_at, current_timestamp)
from public.store_day_variance_cases variance_case
join public.store_day_sessions sds on sds.id = variance_case.store_day_session_id
where not exists (
    select 1 from public.store_day_variance_case_events event
    where event.case_id = variance_case.id
);

insert into public.ibems_schema_meta (version, description)
values ('2026-08-13-variance-governance', 'Add store-day variance cases, evidence retention, independent reviewer handoffs, and legacy variance backfill')
on conflict (version) do nothing;

commit;
