begin;

create table if not exists public.store_capabilities (
    id bigint generated by default as identity primary key,
    store_id bigint not null references public.stores(id) on update cascade on delete cascade,
    capability varchar(40) not null,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    unique (store_id, capability)
);

alter table public.products
    add column if not exists item_type varchar(30) not null default 'stock_item';
alter table public.products
    add column if not exists stock_policy varchar(20) not null default 'tracked';
alter table public.products
    add column if not exists unit_code varchar(20) not null default 'piece';

alter table public.transaction_items
    add column if not exists item_name_snapshot varchar(150);
alter table public.transaction_items
    add column if not exists sku_snapshot varchar(80);
alter table public.transaction_items
    add column if not exists variant_snapshot varchar(100);
alter table public.transaction_items
    add column if not exists unit_code_snapshot varchar(20);
alter table public.transaction_items
    add column if not exists item_type_snapshot varchar(30);

insert into public.store_capabilities (store_id, capability, created_at, updated_at)
select s.id, 'retail', current_timestamp, current_timestamp
from public.stores s
where not exists (
    select 1
    from public.store_capabilities sc
    where sc.store_id = s.id
      and sc.capability = 'retail'
);

commit;
